{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/graphrag/index/run/run_pipeline.py\", line 143, in _run_pipeline\n    result = await workflow_function(config, context)\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/graphrag/index/workflows/extract_graph.py\", line 46, in run_workflow\n    entities, relationships = await extract_graph(\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/graphrag/index/workflows/extract_graph.py\", line 82, in extract_graph\n    extracted_entities, extracted_relationships = await extractor(\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/graphrag/index/operations/extract_graph/extract_graph.py\", line 132, in extract_graph\n    entities = _merge_entities(entity_dfs)\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/graphrag/index/operations/extract_graph/extract_graph.py\", line 156, in _merge_entities\n    all_entities.groupby([\"title\", \"type\"], sort=False)\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/pandas/core/frame.py\", line 9190, in groupby\n    return DataFrameGroupBy(\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/pandas/core/groupby/groupby.py\", line 1329, in __init__\n    grouper, exclusions, obj = get_grouper(\n  File \"/root/mcp-graphrag/.venv/lib/python3.10/site-packages/pandas/core/groupby/grouper.py\", line 1043, in get_grouper\n    raise KeyError(gpr)\nKeyError: 'title'\n",
    "source": "'title'",
    "details": null
}
